### ISSUE TITLE
Extension update 1.4 not working

### ISSUE THREAD

**Issue by darklinkpower** [Gerren/Playnite-MindGame#1]
**Describe the bug**
Extension update 1.4 not working. Updating the extension will not work, upon restart the extension will not be updated correctly and you'll be notified of update again. This means one of these cases:

- Extension manifest was not properly updated to new version
- Installer manifest points to older version
- Version properties in manifests are incorrect

**To Reproduce**
1. Start Playnite. You'll be notified of update
2. Update extension and restart
3. You'll be notified of update upon restart again

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/1389286/218315112-4a341bf1-9659-4124-85ed-e53f7f4a69f6.png)

**Please complete the following information:**
1.2

**Additional context**

**Comment by Gerren** [comment]
Hi there,

Thanks for the feedback! Sadly, on my end it behaves this way too.

I just consulted this with JosefNemec, and it seems something went wrong on the GitHubs side.

But, just now, it just came through on my end. Maybe it is spotty? Maybe it depends to which IP one does connect?

See this [thread](https://github.com/JosefNemec/PlayniteAddonDatabase/pull/260#issuecomment-1426984698)

**Comment by Gerren** [comment]
Btw, you can download the current version [manually](https://github.com/Gerren/Playnite-MindGame/releases/tag/release_1_05).

**Comment by Gerren** [comment]
It really behaves almost randomly. I do not know why. You can inspect the manifests yourself, but AFAIK everything should be fine.

Sometimes it doesn't find any update, sometimes it finds an update, but downloads old version, and ONCE it showed AND downloaded 1.05.

2023-02-12 15_07_24
![2023-02-12 15_07_24-Add-ons…](https://user-images.githubusercontent.com/2953438/218318008-8e8e54d1-5f80-4f80-bbb6-84acb68477b5.png)

2023-02-12 15_10_24
![2023-02-12 15_10_24-Add-ons…](https://user-images.githubusercontent.com/2953438/218317989-f32d626c-6cb0-412d-841b-879016e29e52.png)

2023-02-12 15_47_52
![2023-02-12 15_47_52-Add-ons…](https://user-images.githubusercontent.com/2953438/218318052-dd63fec8-788e-413f-a851-81c72f7bcc64.png)
