### ISSUE TITLE
[QUESTION] - I see sometimes some questions I don't mind at all and I don't want the app to use as filters, for example FPS = 60 as characteristic, what is the best way to exclude those? Don't ask again button?

### ISSUE THREAD

**Issue by Heeervas** [Gerren/Playnite-MindGame#2]
[QUESTION] - I see sometimes some questions I don't mind at all and I don't want the app to use as filters, for example FPS = 60 as characteristic, what is the best way to exclude those? Don't ask again button?

**Comment by Gerren** [comment]
Hi there!

you've got that right! The Don't ask again button adds a question into an ignore list. It is intended for exactly the questions, as you given as an example.

I hope you find a game to play :)

**Comment by Heeervas** [comment]
Thanks! This is great. Really awesome extension, thanks to discovering it I have added like top 1500 metacritic games LOL so it works as my game recommendation engine. Thanks!

**Comment by Gerren** [comment]
Glad to hear it.

If play games through Playnite, I might recommend the [Play Next](https://github.com/SparrowBrain/Playnite.PlayNext) extension by SparrowBrain which works similar to the Steam recommendation queue.

**Comment by Heeervas** [comment]
I also have it but I don't find a sweet spot on Filters, that's why I preferred yours :)
