### ISSUE TITLE
Add option to show excluded filters in a list, add option to keep current selection when leaving MindGame screen 

### ISSUE THREAD

**Issue by Heeervas** [Gerren/Playnite-MindGame#3]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Option to include a list with features/genres/etc that I have marked as not show again to have a better understanding on when to clear filters or not.
Option to keep the current "session" open in the screen of Mind Game so I can check the games on the list (for example if I'm finishing my search and only have 5 games available I prefer to see a video of them than choose by filters.

**Describe alternatives you've considered**
Just suggesting ideas so I have not thought about it. Probably about the first point, have the list inside of settings so we now what we clear when clicking on clear.

**Additional context**
-

**Comment by Gerren** [comment]
Hi there,

the session is solved in version 1.06

As for the settings, they are completely reworked. I hope it will suite your needs. 

I'll close this issue with this comment. Should you have any more ideas, please feel free to open new issue.
