### ISSUE TITLE
Playnite crash on 1.06

### ISSUE THREAD

**Issue by Heeervas** [Gerren/Playnite-MindGame#4]
**Describe the bug**
Configuration does not load on add-on config.
Playnite crash when going into MindGame tab

**To Reproduce**
1. Open Playnite
2. Click on Add-Ons
3. Find Mind-game settings

1. Open Playnite
2. Click on Mind Game tab
3. See how Playnite crash.

**Expected behavior**
That Playnite doesn´t crash.

**Screenshots**

**Please complete the following information:**
 - Version 1.0.6

**Additional context**
Log:
02-10 10:36:46.057|ERROR|PlayniteApplication:Unhandled exception occured.
System.ArgumentNullException: El valor no puede ser nulo.
Nombre del parámetro: source
   en System.Linq.Enumerable.Select[TSource,TResult](IEnumerable`1 source, Func`2 selector)
   en MindGame.MindGameSettingsViewModel.<Init>b__18_0(IMindGameProperty type) en E:\Zaloha\Projects\Playnite\MindGame\MindGame\Models\MindGameSettings.cs:línea 186
   en System.Collections.Generic.List`1.ForEach(Action`1 action)
   en MindGame.MindGameSettingsViewModel.Init() en E:\Zaloha\Projects\Playnite\MindGame\MindGame\Models\MindGameSettings.cs:línea 174
   en MindGame.MindGameSettingsViewModel..ctor(MindGamePlugin plugin) en E:\Zaloha\Projects\Playnite\MindGame\MindGame\Models\MindGameSettings.cs:línea 141
   en MindGame.MindGamePlugin.get_settings() en E:\Zaloha\Projects\Playnite\MindGame\MindGame\MindGamePlugin.cs:línea 30
   en MindGame.MindGamePlugin.get_Settings() en E:\Zaloha\Projects\Playnite\MindGame\MindGame\MindGamePlugin.cs:línea 36
   en MindGame.Models.MindGameSelectGameViewModel.<>c__DisplayClass43_0.<Next>b__4(IMindGameProperty p) en E:\Zaloha\Projects\Playnite\MindGame\MindGame\Models\MindGameSelectGameViewModel.cs:línea 144
   en System.Linq.Enumerable.WhereArrayIterator`1.MoveNext()
   en System.Linq.Enumerable.Any[TSource](IEnumerable`1 source)
   en System.Collections.Generic.ListExtensions.HasItems[T](IEnumerable`1 source) en C:\projects\playnite\source\PlayniteSDK\Extensions\ListExtensions.cs:línea 39
   en System.Collections.Generic.ListExtensions.ForEach[T](IEnumerable`1 source, Action`1 action) en C:\projects\playnite\source\PlayniteSDK\Extensions\ListExtensions.cs:línea 446
   en MindGame.Models.MindGameSelectGameViewModel.Next() en E:\Zaloha\Projects\Playnite\MindGame\MindGame\Models\MindGameSelectGameViewModel.cs:línea 143
   en MindGame.Models.MindGameSelectGameViewModel.DoInit() en E:\Zaloha\Projects\Playnite\MindGame\MindGame\Models\MindGameSelectGameViewModel.cs:línea 40
   en MindGame.Models.MindGameSelectGameViewModel.Init() en E:\Zaloha\Projects\Playnite\MindGame\MindGame\Models\MindGameSelectGameViewModel.cs:línea 57
   en MindGame.Views.MindGameSelectGameView.Init() en E:\Zaloha\Projects\Playnite\MindGame\MindGame\Views\MindGameSelectGameView.xaml.cs:línea 37
   en MindGame.MindGamePlugin.MindGameViewSidebar.<>c.<.ctor>b__0_0() en E:\Zaloha\Projects\Playnite\MindGame\MindGame\MindGamePlugin.cs:línea 75
   en Playnite.DesktopApp.ViewModels.SidebarWrapperItem.Activation(Object arg) en C:\projects\playnite\source\Playnite.DesktopApp\ViewModels\DesktopAppViewModel_Sidebar.cs:línea 130
   en Playnite.SDK.RelayCommand`1.Execute(Object parameter) en C:\projects\playnite\source\PlayniteSDK\RelayCommand.cs:línea 205
   en MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(ICommandSource commandSource, Boolean userInitiated)
   en System.Windows.Controls.Primitives.ButtonBase.OnClick()
   en System.Windows.Controls.Button.OnClick()
   en System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   en System.Windows.UIElement.OnMouseLeftButtonUpThunk(Object sender, MouseButtonEventArgs e)
   en System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   en System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   en System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   en System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   en System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   en System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
   en System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   en System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   en System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   en System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   en System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   en System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   en System.Windows.UIElement.RaiseEvent(RoutedEventArgs args, Boolean trusted)
   en System.Windows.Input.InputManager.ProcessStagingArea()
   en System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   en System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   en System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   en System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   en System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   en MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   en MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   en System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   en System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   en System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   en MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   en MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   en System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   en System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   en System.Windows.Application.RunDispatcher(Object ignore)
   en System.Windows.Application.RunInternal(Window window)
   en System.Windows.Application.Run(Window window)
   en Playnite.DesktopApp.ProgramEntry.Main(String[] args) en C:\projects\playnite\source\Playnite.DesktopApp\ProgramEntry.cs:línea 61

**Comment by Gerren** [comment]
Yup, that's a bug. It was an initialization. Should be fixed in 1.07
